export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL'; // Yeni action type
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const SET_FAVORITES = 'SET_FAVORITES';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const LOGOUT = 'LOGOUT';
export const SET_USER = 'SET_USER'; // Yeni eklenen action type
export const ADD_TO_SEPET = 'ADD_TO_SEPET';
export const REMOVE_FROM_SEPET = 'REMOVE_FROM_SEPET';